"use client"

import { useState, useEffect } from "react"
import { supabase, type MenuItem } from "@/lib/supabase"

// Menu lengkap dengan kategori yang sudah diperbaiki (tanpa TAKE AWAY)
const COMPLETE_MENU_ITEMS: MenuItem[] = [
  // MIE CATEGORY (15 items)
  {
    id: "mie-1",
    name: "MIE SUIT",
    price: 10500,
    image_url: "/images/food-menu.png",
    category: "MIE",
    is_available: true,
    description: "Mie dengan bumbu khas Mie Gacoan yang lezat",
    spice_level: 0,
    created_at: new Date().toISOString(),
  },
  {
    id: "mie-2",
    name: "MIE GACOAN LEVEL 0",
    price: 10500,
    image_url: "/images/mie-gacoan-level-1.png",
    category: "MIE",
    is_available: true,
    description: "Mie Gacoan tanpa pedas, cocok untuk semua usia",
    spice_level: 0,
    created_at: new Date().toISOString(),
  },
  {
    id: "mie-3",
    name: "MIE GACOAN LEVEL 1",
    price: 10500,
    image_url: "/images/mie-gacoan-level-1.png",
    category: "MIE",
    is_available: true,
    description: "Mie Gacoan dengan tingkat kepedasan ringan",
    spice_level: 1,
    created_at: new Date().toISOString(),
  },
  {
    id: "mie-4",
    name: "MIE GACOAN LEVEL 2",
    price: 10500,
    image_url: "/images/mie-gacoan-level-2.png",
    category: "MIE",
    is_available: true,
    description: "Mie Gacoan dengan tingkat kepedasan sedang",
    spice_level: 2,
    created_at: new Date().toISOString(),
  },
  {
    id: "mie-5",
    name: "MIE GACOAN LEVEL 3",
    price: 10500,
    image_url: "/images/mie-gacoan-level-3.png",
    category: "MIE",
    is_available: true,
    description: "Mie Gacoan dengan tingkat kepedasan tinggi",
    spice_level: 3,
    created_at: new Date().toISOString(),
  },
  {
    id: "mie-6",
    name: "MIE GACOAN LEVEL 4",
    price: 10500,
    image_url: "/images/mie-gacoan-level-3.png",
    category: "MIE",
    is_available: true,
    description: "Mie Gacoan dengan tingkat kepedasan sangat tinggi",
    spice_level: 4,
    created_at: new Date().toISOString(),
  },
  {
    id: "mie-7",
    name: "MIE GACOAN LEVEL 5",
    price: 11400,
    image_url: "/images/mie-gacoan-level-3.png",
    category: "MIE",
    is_available: true,
    description: "Mie Gacoan dengan tingkat kepedasan ekstrem",
    spice_level: 5,
    created_at: new Date().toISOString(),
  },
  {
    id: "mie-8",
    name: "MIE GACOAN LEVEL 6",
    price: 11400,
    image_url: "/images/mie-gacoan-level-3.png",
    category: "MIE",
    is_available: true,
    description: "Mie Gacoan dengan tingkat kepedasan level 6",
    spice_level: 6,
    created_at: new Date().toISOString(),
  },
  {
    id: "mie-9",
    name: "MIE GACOAN LEVEL 7",
    price: 11400,
    image_url: "/images/mie-gacoan-level-3.png",
    category: "MIE",
    is_available: true,
    description: "Mie Gacoan dengan tingkat kepedasan level 7",
    spice_level: 7,
    created_at: new Date().toISOString(),
  },
  {
    id: "mie-10",
    name: "MIE GACOAN LEVEL 8",
    price: 11400,
    image_url: "/images/mie-gacoan-level-3.png",
    category: "MIE",
    is_available: true,
    description: "Mie Gacoan dengan tingkat kepedasan maksimal",
    spice_level: 8,
    created_at: new Date().toISOString(),
  },
  {
    id: "mie-11",
    name: "MIE AYAM GEPREK",
    price: 15000,
    image_url: "/images/mie-gacoan-level-2.png",
    category: "MIE",
    is_available: true,
    description: "Mie dengan ayam geprek pedas",
    spice_level: 2,
    created_at: new Date().toISOString(),
  },
  {
    id: "mie-12",
    name: "MIE SEAFOOD",
    price: 18000,
    image_url: "/images/mie-gacoan-level-2.png",
    category: "MIE",
    is_available: true,
    description: "Mie dengan topping seafood segar",
    spice_level: 1,
    created_at: new Date().toISOString(),
  },
  {
    id: "mie-13",
    name: "MIE TELUR CEPLOK",
    price: 12000,
    image_url: "/images/mie-gacoan-level-1.png",
    category: "MIE",
    is_available: true,
    description: "Mie dengan telur ceplok",
    spice_level: 1,
    created_at: new Date().toISOString(),
  },
  {
    id: "mie-14",
    name: "MIE JUMBO",
    price: 16000,
    image_url: "/images/mie-gacoan-level-2.png",
    category: "MIE",
    is_available: true,
    description: "Mie dengan porsi jumbo",
    spice_level: 2,
    created_at: new Date().toISOString(),
  },
  {
    id: "mie-15",
    name: "MIE SPECIAL",
    price: 20000,
    image_url: "/images/mie-gacoan-level-3.png",
    category: "MIE",
    is_available: true,
    description: "Mie special dengan topping lengkap",
    spice_level: 3,
    created_at: new Date().toISOString(),
  },

  // DIMSUM CATEGORY (12 items)
  {
    id: "dimsum-1",
    name: "SIOMAY",
    price: 9500,
    image_url: "/images/siomay.png",
    category: "DIMSUM",
    is_available: true,
    description: "Siomay kukus dengan bumbu kacang",
    spice_level: 0,
    created_at: new Date().toISOString(),
  },
  {
    id: "dimsum-2",
    name: "UDANG RAMBUTAN",
    price: 9500,
    image_url: "/images/udang-keju.png",
    category: "DIMSUM",
    is_available: true,
    description: "Udang dengan saus rambutan yang unik",
    spice_level: 0,
    created_at: new Date().toISOString(),
  },
  {
    id: "dimsum-3",
    name: "UDANG KEJU",
    price: 9500,
    image_url: "/images/udang-keju.png",
    category: "DIMSUM",
    is_available: true,
    description: "Udang dengan topping keju yang melted",
    spice_level: 0,
    created_at: new Date().toISOString(),
  },
  {
    id: "dimsum-4",
    name: "LUMPIA UDANG",
    price: 9500,
    image_url: "/images/udang-keju.png",
    category: "DIMSUM",
    is_available: true,
    description: "Lumpia segar dengan isian udang dan sayuran",
    spice_level: 0,
    created_at: new Date().toISOString(),
  },
  {
    id: "dimsum-5",
    name: "PANGSIT GORENG",
    price: 10500,
    image_url: "/images/siomay.png",
    category: "DIMSUM",
    is_available: true,
    description: "Pangsit goreng renyah dengan isian daging",
    spice_level: 0,
    created_at: new Date().toISOString(),
  },
  {
    id: "dimsum-6",
    name: "HAKAU",
    price: 9500,
    image_url: "/images/siomay.png",
    category: "DIMSUM",
    is_available: true,
    description: "Hakau udang dengan kulit transparan",
    spice_level: 0,
    created_at: new Date().toISOString(),
  },
  {
    id: "dimsum-7",
    name: "PANGSIT REBUS",
    price: 9500,
    image_url: "/images/siomay.png",
    category: "DIMSUM",
    is_available: true,
    description: "Pangsit rebus dengan kuah gurih",
    spice_level: 0,
    created_at: new Date().toISOString(),
  },
  {
    id: "dimsum-8",
    name: "BAKSO IKAN",
    price: 8500,
    image_url: "/images/siomay.png",
    category: "DIMSUM",
    is_available: true,
    description: "Bakso ikan segar dengan tekstur kenyal",
    spice_level: 0,
    created_at: new Date().toISOString(),
  },
  {
    id: "dimsum-9",
    name: "TAHU ISI",
    price: 7500,
    image_url: "/images/siomay.png",
    category: "DIMSUM",
    is_available: true,
    description: "Tahu goreng dengan isian sayuran",
    spice_level: 0,
    created_at: new Date().toISOString(),
  },
  {
    id: "dimsum-10",
    name: "UDANG MAYONES",
    price: 11000,
    image_url: "/images/udang-keju.png",
    category: "DIMSUM",
    is_available: true,
    description: "Udang dengan saus mayones creamy",
    spice_level: 0,
    created_at: new Date().toISOString(),
  },
  {
    id: "dimsum-11",
    name: "CEKER MERCON",
    price: 12000,
    image_url: "/images/siomay.png",
    category: "DIMSUM",
    is_available: true,
    description: "Ceker ayam dengan bumbu pedas mercon",
    spice_level: 4,
    created_at: new Date().toISOString(),
  },
  {
    id: "dimsum-12",
    name: "DIMSUM COMBO",
    price: 25000,
    image_url: "/images/siomay.png",
    category: "DIMSUM",
    is_available: true,
    description: "Paket combo berbagai dimsum pilihan",
    spice_level: 0,
    created_at: new Date().toISOString(),
  },

  // MINUMAN DINGIN CATEGORY (15 items)
  {
    id: "cold-1",
    name: "ES GOBAK SODOR",
    price: 9500,
    image_url: "/images/es-buah.png",
    category: "MINUMAN DINGIN",
    is_available: true,
    description: "Es buah dengan nama unik khas Jawa",
    spice_level: 0,
    created_at: new Date().toISOString(),
  },
  {
    id: "cold-2",
    name: "ES TEKLEK",
    price: 6400,
    image_url: "/images/es-buah.png",
    category: "MINUMAN DINGIN",
    is_available: true,
    description: "Es buah segar dengan campuran buah lokal",
    spice_level: 0,
    created_at: new Date().toISOString(),
  },
  {
    id: "cold-3",
    name: "ES SLUKU BATHOK",
    price: 6400,
    image_url: "/images/es-buah.png",
    category: "MINUMAN DINGIN",
    is_available: true,
    description: "Es kelapa muda dengan gula aren",
    spice_level: 0,
    created_at: new Date().toISOString(),
  },
  {
    id: "cold-4",
    name: "ES PETAK UMPET",
    price: 9500,
    image_url: "/images/es-buah.png",
    category: "MINUMAN DINGIN",
    is_available: true,
    description: "Es buah dengan berbagai topping tersembunyi",
    spice_level: 0,
    created_at: new Date().toISOString(),
  },
  {
    id: "cold-5",
    name: "ES CINCAU",
    price: 5500,
    image_url: "/images/es-buah.png",
    category: "MINUMAN DINGIN",
    is_available: true,
    description: "Es cincau hitam dengan sirup gula merah",
    spice_level: 0,
    created_at: new Date().toISOString(),
  },
  {
    id: "cold-6",
    name: "ES KELAPA MUDA",
    price: 8000,
    image_url: "/images/es-buah.png",
    category: "MINUMAN DINGIN",
    is_available: true,
    description: "Es kelapa muda segar langsung dari buah",
    spice_level: 0,
    created_at: new Date().toISOString(),
  },
  {
    id: "cold-7",
    name: "LEMON TEA ICE",
    price: 6800,
    image_url: "/images/kopi-latte.png",
    category: "MINUMAN DINGIN",
    is_available: true,
    description: "Teh lemon segar dengan es batu",
    spice_level: 0,
    created_at: new Date().toISOString(),
  },
  {
    id: "cold-8",
    name: "ICED COFFEE",
    price: 8600,
    image_url: "/images/kopi-latte.png",
    category: "MINUMAN DINGIN",
    is_available: true,
    description: "Kopi dingin yang menyegarkan",
    spice_level: 0,
    created_at: new Date().toISOString(),
  },
  {
    id: "cold-9",
    name: "ICED LATTE",
    price: 12000,
    image_url: "/images/kopi-latte.png",
    category: "MINUMAN DINGIN",
    is_available: true,
    description: "Latte dingin dengan foam yang creamy",
    spice_level: 0,
    created_at: new Date().toISOString(),
  },
  {
    id: "cold-10",
    name: "THAI TEA ICE",
    price: 8600,
    image_url: "/images/kopi-latte.png",
    category: "MINUMAN DINGIN",
    is_available: true,
    description: "Thai tea dingin dengan rasa yang khas",
    spice_level: 0,
    created_at: new Date().toISOString(),
  },
  {
    id: "cold-11",
    name: "GREEN TEA ICE",
    price: 7500,
    image_url: "/images/kopi-latte.png",
    category: "MINUMAN DINGIN",
    is_available: true,
    description: "Green tea dingin yang menyegarkan",
    spice_level: 0,
    created_at: new Date().toISOString(),
  },
  {
    id: "cold-12",
    name: "CHOCOLATE ICE",
    price: 8600,
    image_url: "/images/kopi-latte.png",
    category: "MINUMAN DINGIN",
    is_available: true,
    description: "Coklat dingin yang creamy",
    spice_level: 0,
    created_at: new Date().toISOString(),
  },
  {
    id: "cold-13",
    name: "ORANGE JUICE",
    price: 7000,
    image_url: "/images/es-buah.png",
    category: "MINUMAN DINGIN",
    is_available: true,
    description: "Jus jeruk segar dengan es batu",
    spice_level: 0,
    created_at: new Date().toISOString(),
  },
  {
    id: "cold-14",
    name: "MANGO JUICE",
    price: 8500,
    image_url: "/images/es-buah.png",
    category: "MINUMAN DINGIN",
    is_available: true,
    description: "Jus mangga segar dan manis",
    spice_level: 0,
    created_at: new Date().toISOString(),
  },
  {
    id: "cold-15",
    name: "AIR MINERAL",
    price: 4500,
    image_url: "/images/kopi-latte.png",
    category: "MINUMAN DINGIN",
    is_available: true,
    description: "Air mineral dalam kemasan botol",
    spice_level: 0,
    created_at: new Date().toISOString(),
  },

  // MINUMAN PANAS CATEGORY (10 items)
  {
    id: "hot-1",
    name: "TEH TARIK PANAS",
    price: 6800,
    image_url: "/images/kopi-latte.png",
    category: "MINUMAN PANAS",
    is_available: true,
    description: "Teh tarik panas dengan foam yang creamy",
    spice_level: 0,
    created_at: new Date().toISOString(),
  },
  {
    id: "hot-2",
    name: "KOPI HITAM",
    price: 5500,
    image_url: "/images/kopi-latte.png",
    category: "MINUMAN PANAS",
    is_available: true,
    description: "Kopi hitam panas yang strong",
    spice_level: 0,
    created_at: new Date().toISOString(),
  },
  {
    id: "hot-3",
    name: "CAPPUCCINO",
    price: 12000,
    image_url: "/images/kopi-latte.png",
    category: "MINUMAN PANAS",
    is_available: true,
    description: "Cappuccino panas dengan foam yang sempurna",
    spice_level: 0,
    created_at: new Date().toISOString(),
  },
  {
    id: "hot-4",
    name: "LATTE PANAS",
    price: 12000,
    image_url: "/images/kopi-latte.png",
    category: "MINUMAN PANAS",
    is_available: true,
    description: "Latte panas yang aromatic",
    spice_level: 0,
    created_at: new Date().toISOString(),
  },
  {
    id: "hot-5",
    name: "HOT CHOCOLATE",
    price: 8600,
    image_url: "/images/kopi-latte.png",
    category: "MINUMAN PANAS",
    is_available: true,
    description: "Coklat panas yang hangat dan nikmat",
    spice_level: 0,
    created_at: new Date().toISOString(),
  },
  {
    id: "hot-6",
    name: "TEH MANIS PANAS",
    price: 4500,
    image_url: "/images/kopi-latte.png",
    category: "MINUMAN PANAS",
    is_available: true,
    description: "Teh manis panas yang hangat",
    spice_level: 0,
    created_at: new Date().toISOString(),
  },
  {
    id: "hot-7",
    name: "JAHE HANGAT",
    price: 6000,
    image_url: "/images/kopi-latte.png",
    category: "MINUMAN PANAS",
    is_available: true,
    description: "Minuman jahe hangat untuk kesehatan",
    spice_level: 1,
    created_at: new Date().toISOString(),
  },
  {
    id: "hot-8",
    name: "WEDANG RONDE",
    price: 7500,
    image_url: "/images/kopi-latte.png",
    category: "MINUMAN PANAS",
    is_available: true,
    description: "Wedang ronde hangat dengan isian kacang",
    spice_level: 0,
    created_at: new Date().toISOString(),
  },
  {
    id: "hot-9",
    name: "BANDREK",
    price: 7000,
    image_url: "/images/kopi-latte.png",
    category: "MINUMAN PANAS",
    is_available: true,
    description: "Bandrek hangat dengan rempah-rempah",
    spice_level: 1,
    created_at: new Date().toISOString(),
  },
  {
    id: "hot-10",
    name: "SUSU HANGAT",
    price: 6500,
    image_url: "/images/kopi-latte.png",
    category: "MINUMAN PANAS",
    is_available: true,
    description: "Susu hangat yang menenangkan",
    spice_level: 0,
    created_at: new Date().toISOString(),
  },
]

export function useSupabaseMenu() {
  const [menuItems, setMenuItems] = useState<MenuItem[]>([])
  const [loading, setLoading] = useState(true)
  const [error, setError] = useState<string | null>(null)

  useEffect(() => {
    fetchMenuItems()
  }, [])

  const fetchMenuItems = async () => {
    try {
      setLoading(true)

      // Check if Supabase is properly configured
      const isSupabaseConfigured =
        process.env.NEXT_PUBLIC_SUPABASE_URL &&
        process.env.NEXT_PUBLIC_SUPABASE_URL !== "https://your-project.supabase.co"

      if (!isSupabaseConfigured) {
        // Use complete menu data for development
        console.log("Using complete menu data - Supabase not configured")
        setMenuItems(COMPLETE_MENU_ITEMS)
        setLoading(false)
        return
      }

      const { data, error } = await supabase
        .from("menu_items")
        .select("*")
        .eq("is_available", true)
        .order("created_at", { ascending: true })

      if (error) throw error
      setMenuItems(data || [])
    } catch (err) {
      console.error("Error fetching menu items:", err)
      // Fallback to complete menu data on error
      setMenuItems(COMPLETE_MENU_ITEMS)
      setError(err instanceof Error ? err.message : "An error occurred")
    } finally {
      setLoading(false)
    }
  }

  return { menuItems, loading, error, refetch: fetchMenuItems }
}
